<?php

namespace Webclusive\Bundle\LunchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DateStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateStateRepository extends EntityRepository
{
}
