<?php

namespace Webclusive\Bundle\LunchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DateStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateStateRepository extends EntityRepository
{

    public function countLunchesByUser($user)
    {
        $qb = $this->createQueryBuilder('ds');

        $qb->select('count(ds.id)');
        $qb->andWhere('user = :user');
        $qb->andWhere('state = :state');

        $qb->setParameter(':user', $user);
        $qb->setParameter(':state', DateState::STATE_LUNCH);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
