<?php

namespace Webclusive\Bundle\LunchBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getAllWithCurrentLunchCount()
    {
        $qb = $this->createQueryBuilder('u');

        $qb->addSelect('COUNT(ds.id) as totalCount');
        $qb->leftJoin('u.dateStates', 'ds', Join::WITH, 'u.id = ds.user AND ds.state = :state AND ds.targetDate < :today');
        $qb->groupBy('u.id');


        $qb->setParameter(':state', DateState::STATE_LUNCH);
        $qb->setParameter(':today', new \DateTime('today'));

        return $qb->getQuery()->getResult();
    }
}
